---
seasons:
  - name: Corinthians
    start: Aug 1, 2025
    days: 365
    meets:

      - name: Scramble
        start: Sep 13 2025 9 AM PDT
        special_material: 1 Cor 1-3
        deadline: 0
        host:
            name: Heartwood Church
            url: https://heartwoodchurchwa.org
            address: 19320 SE 240th St, Covington WA 98042
        notes: No registration required

      - name: Meet 1
        region: OR

      - name: Meet 2
        start: Nov 22 2025 8 AM PST
        new_material: 1 Cor 8-12
        host:
            name: Elk Plain Community Church
            url: http://elkplain.org
            address: 4115 224th St E, Spanaway WA 98387
            housing: true
            lunch: true

      - name: Meet 3
        start: Jan 10 2026 8 AM PST
        new_material: 1 Cor 13-16
        host:
            name: Eastridge Baptist Church
            url: https://eastridgebaptist.org
            address: 12520 SE 240th St, Kent WA 98031

      - name: Meet 4
        start: Feb 7 2026 8 AM PST
        deadline: 7
        new_material: 2 Cor 1-5
        host:
            name: Burley Bible Church
            url: https://bbcol.org
            address: 14687 Olympic Dr SE, Port Orchard WA 98367
            housing: true
            lunch: true

      - name: Meet 5
        start: Mar 21 2026 8 AM PDT
        new_material: 2 Cor 6-13
        host:
            name: Highlands Community Church
            url: https://highlandscc.org
            address: 3031 NE Tenth St, Renton WA 98056
            housing: true
            lunch: true

      - name: Championships
        start: May 1 2026 5 PM PDT
        days: 2
        host:
            name: Double K Retreat Center
            url: https://doublek.org
            address: 620 Tall Timber Trail, Easton WA 98925
            housing: true
            lunch: true
        notes: |
            - Arrive Friday for dinner followed by Quizzing that evening
            - Quizzing continues Saturday and concludes with finals and awards prior to dinner
